#!/bin/bash
set -e

TARGET_VERSION=$(cargo pkgid | cut -d# -f2 | cut -d: -f2)

# Create docker image
docker build . --file Dockerfile --tag inclusionmtl/dashboard-api:"$TARGET_VERSION" --tag inclusionmtl/dashboard-api:latest
